name = "iipython-status-page"
main = "fetch_status.js"
compatibility_date = "2024-09-28"

# Fuck off Cloudflare
workers_dev = false
send_metrics = false

# Force enable keeping logs
[observability]
enabled = true

# Fetch data every hour
[triggers]
crons = ["0 * * * *"]

# Setup KV
[[kv_namespaces]]
binding = "statuspage_data"
id = "80f4f9f46ae84fb18aa2038717aabdfb"
