name: Minify HTML
on:
  push:
    paths:
      - "src/**"

jobs:
  checkout-minify-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
            node-version: "16"
      - run: npm install -g html-minifier
      - run: html-minifier --collapse-boolean-attributes --collapse-whitespace --minify-css --minify-js --minify-urls --remove-attribute-quotes --remove-comments --remove-empty-attributes --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-style-link-type-attributes --remove-tag-whitespace -o index.html src/index.html
      - run: |
          git config user.name 'statuspage'
          git config user.email status@iipython.dev
          git add .
          git commit -am '[Automated] Minify ${{ github.sha }}'
          git push origin main