name: Update Status
on:
  schedule:
    - cron: "0 * * * *"

jobs:
  status_check_job:
    runs-on: ubuntu-latest
    name: Check all sites
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install requests
        run: |
          python -VV
          python -m pip install --upgrade requests
      - name: Perform Status Check
        run: python ./src/status_check.py
